export const employee = [
  {
    relativeUrl:
      "https://img.freepik.com/free-photo/abstract-colorful-splash-3d-background-generative-ai-background_60438-2510.jpg",
    absoluteUrl: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    name: "Muthuramkumaran B",
    role: "HR manager",
    branch:"Kovilpatti",
    email:"muthuram12@mitrahsoft.com",
    phone:"9524449342",
    joinedDate:"June 23,2022",
    gender:"Male",
    birthdayDate:"November 23,1998",
    employeeNumber:"CF5096",
    reportingTo:"Manimaran",
    shiftTime:"10.30 to 8.30",
  },
  {
    relativeUrl:
      "https://img.freepik.com/premium-photo/organic-abstract-gradient-wallpaper-background-header-illustration_692702-9499.jpg",
    absoluteUrl: "https://cdn-icons-png.flaticon.com/512/168/168726.png",
    name: "Dineshkumar S",
    role: "Business Development Executive",
    branch:"Kovilpatti",
    email:"dinesh12@mitrahsoft.com",
    phone:"8524449342",
    joinedDate:"July 23,2023",
    gender:"Male",
    birthdayDate:"January 23,1997",
    employeeNumber:"BD5096",
    reportingTo:"Manimaran",
    shiftTime:"11.00 to 9.00",
  },
  {
    relativeUrl:
      "https://img.freepik.com/premium-photo/creative-abstract-3d-background-wallpaper-texture-abstract-3d-watercolor-background_372999-8823.jpg",
      absoluteUrl:
      "https://static.vecteezy.com/system/resources/thumbnails/004/607/791/small/man-face-emotive-icon-smiling-male-character-in-blue-shirt-flat-illustration-isolated-on-white-happy-human-psychological-portrait-positive-emotions-user-avatar-for-app-web-design-vector.jpg",
    name: "Gopinath M",
    role: "Business Development Executive",
    branch:"Coimbatore",
    email:"gopi12@mitrahsoft.com",
    phone:"7524449342",
    joinedDate:"June 23,2022",
    gender:"Male",
    birthdayDate:"December 23,1998",
    employeeNumber:"BD5126",
    reportingTo:"Manimaran",
    shiftTime:"11.00 to 9.00",
  },
  {
    relativeUrl:
      "https://img.freepik.com/free-photo/abstract-colorful-splash-3d-background-generative-ai-background_60438-2509.jpg?w=2000",
    absoluteUrl:
      "https://cdn.create.vista.com/api/media/small/113265060/stock-vector-female-avatar-icon",
    name: "Abishek J",
    role: "MERN stack Developer",
    branch:"Madurai",
    email:"abi12@mitrahsoft.com",
    phone:"6524449342",
    joinedDate:"October 23,2022",
    gender:"Male",
    birthdayDate:"March 23,2001",
    employeeNumber:"RT3456",
    reportingTo:"Manimaran",
    shiftTime:"10.30 to 8.30",
  },
  {
    relativeUrl:
      "https://img.freepik.com/fotos-premium/pintura-colorida-toque-pintura-bola-azul_691900-108.jpg",
    absoluteUrl:
      "https://static.vecteezy.com/system/resources/thumbnails/004/607/791/small/man-face-emotive-icon-smiling-male-character-in-blue-shirt-flat-illustration-isolated-on-white-happy-human-psychological-portrait-positive-emotions-user-avatar-for-app-web-design-vector.jpg",
    name: "Abubacker Siddiq A",
    role: "React Native Developer",
    branch:"Kovilpatti",
    email:"abu12@mitrahsoft.com",
    phone:"9452444934",
    joinedDate:"October 23,2022",
    gender:"Male",
    birthdayDate:"April 23,1998",
    employeeNumber:"RT5096",
    reportingTo:"Manimaran",
    shiftTime:"10.30 to 8.30",
  },
  {
    relativeUrl:
      "https://img.freepik.com/fotos-premium/colorido-remolino-colores-claros-oscuros-fondo-negro_883586-11607.jpg",
    absoluteUrl:
      "https://creazilla-store.fra1.digitaloceanspaces.com/icons/7912990/avatar-icon-md.png",
    name: "Manikandan K",
    role: "MERN stack Developer",
    branch:"Kovilpatti",
    email:"mani22@mitrahsoft.com",
    phone:"89244442",
    joinedDate:"June 23,2022",
    gender:"Male",
    birthdayDate:"November 23,1998",
    employeeNumber:"CF5096",
    reportingTo:"Manimaran",
    shiftTime:"9.00 to 7.00",
  },
  {
    relativeUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROZKrELDEtX_IfUoRRZW26SNZcVxImQqiSF3mbmi8SR0sEDjNrUn9FCueJYM4Wyo86_Wg&usqp=CAU",
    absoluteUrl:
      "https://images.vexels.com/content/145908/preview/male-avatar-maker-2a7919.png",
    name: "Manikandan R",
    role: "React Developer",
    branch:"Coimbatore",
    email:"mani12@mitrahsoft.com",
    phone:"9524449342",
    joinedDate:"June 23,2022",
    gender:"Male",
    birthdayDate:"November 23,1998",
    employeeNumber:"CF5096",
    reportingTo:"Manimaran",
    shiftTime:"10.30 to 8.30",
  },
  {
    relativeUrl:
      "https://img.freepik.com/premium-photo/abstract-background-colorful-wallpaper-made-by-aiartificial-intelligence_41969-12368.jpg",
    absoluteUrl:
      "https://img.redro.pl/obrazy/man-avatar-icon-700-245635972.jpg",
    name: "MariGanesh B",
    role: "MERN stack Developer",
    branch:"Kovilpatti",
    email:"mari12@mitrahsoft.com",
    phone:"6924449342",
    joinedDate:"June 23,2022",
    gender:"Male",
    birthdayDate:"November 23,1998",
    employeeNumber:"CF5096",
    reportingTo:"Manimaran",
    shiftTime:"10.30 to 8.30",
  },
  {
    relativeUrl:
      " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8IMfqd6D-0R-Lsfz13xpfkoMICJO_i7xH7nZbeHuTwegC5cycpBDNecFRbcL3EpLpXY0&usqp=CAU",
    absoluteUrl: "https://cdn-icons-png.flaticon.com/512/168/168723.png",
    name: "Prasanth V",
    role: "Angular Developer",
    branch:"Kovilpatti",
    email:"prasanth12@mitrahsoft.com",
    phone:"6467892634",
    joinedDate:"June 23,2022",
    gender:"Male",
    birthdayDate:"November 23,1998",
    employeeNumber:"CF5096",
    reportingTo:"Manimaran",
    shiftTime:"10.30 to 8.30",
  },
  {
    relativeUrl:
      "https://t4.ftcdn.net/jpg/03/12/45/29/360_F_312452954_hU8Jthl9GWB31LQjbcBubPTA21oGgfxD.jpg",
      absoluteUrl:
      "https://www.shareicon.net/download/2016/07/05/791225_man_512x512.png",
      name: "Rekha S",
    role: "Tester",
    branch:"Kovilpatti",
    email:"rekha12@mitrahsoft.com",
    phone:"9524449342",
    joinedDate:"June 23,2022",
    gender:"Female",
    birthdayDate:"November 23,1998",
    employeeNumber:"CF5096",
    reportingTo:"Manimaran",
    shiftTime:"10.30 to 8.30",
  },
  {
    relativeUrl:
      "https://t4.ftcdn.net/jpg/04/44/57/03/360_F_444570336_1R7JqCgrLOGoYHIDC23bsp4vnBj8UvT0.jpg",
    absoluteUrl:
      "https://wallpapers.com/images/hd/naruto-profile-pictures-sa1tekghfajrr928.jpg",
    name: "Revankumar P",
    role: "React Developer",
    branch:"Madurai",
    email:"revan12@mitrahsoft.com",
    phone:"9524449342",
    joinedDate:"June 23,2022",
    gender:"Male",
    birthdayDate:"November 23,1998",
    employeeNumber:"CF5096",
    reportingTo:"Manimaran",
    shiftTime:"10.30 to 8.30",
  },
  {
    relativeUrl:
      "https://t4.ftcdn.net/jpg/05/50/70/59/360_F_550705975_e4jJQi1lYt1Jeeb3vHPWtoGQ3mS2Zwyl.webp",
    absoluteUrl:
      " https://socialmarketbooster.com/wp-content/themes/socialbooster/assets/images/forSlideColRPic2.jpg",
    name: "Sathishkumar VC",
    role: "React Developer",
    branch:"Kovilpatti",
    email:"sathish12@mitrahsoft.com",
    phone:"923145242",
    joinedDate:"June 23,2022",
    gender:"Male",
    birthdayDate:"November 23,1998",
    employeeNumber:"CF5096",
    reportingTo:"Manimaran",
    shiftTime:"10.30 to 8.30",
  },
  {
    relativeUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg2CGTkasQbVaHhE2BlV47ob5xjZ0syqW3WGTqh4zgdg_fZX3rTgEKsI5oT3qNPIhfv5Y&usqp=CAU",
    absoluteUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtc_TaWjbx-6Sfcq3nBfaAMTqMurH3xJ0JO2hoc6wvWQ6hFYkhxW1wxSd_DQwwSn7cAfk&usqp=CAU",
    name: "Vishva S",
    role: "React Developer",
    branch:"Kovilpatti",
    email:"vishva12@mitrahsoft.com",
    phone:"6369366909",
    joinedDate:"June 23,2022",
    gender:"Male",
    birthdayDate:"November 23,1998",
    employeeNumber:"CF5096",
    reportingTo:"Manimaran",
    shiftTime:"10.30 to 8.30",
  },
  {
    relativeUrl:
      "https://w0.peakpx.com/wallpaper/390/39/HD-wallpaper-compulsory-abstract-abstract.jpg",
    absoluteUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYoyLDe8MY1zE0d0D7ssSl-PsQEHFkIAsWproOPwmdt4vpajwck5o93Av0h8_7LybI5zw&usqp=CAU",
    name: "Boopesh T",
    role: "React Developer",
    branch:"Coimbatore",
    email:"boopesh12@mitrahsoft.com",
    phone:"6346523466",
    joinedDate:"June 23,2022",
    gender:"Male",
    birthdayDate:"November 23,1998",
    employeeNumber:"CF5096",
    reportingTo:"Manimaran",
    shiftTime:"10.30 to 8.30",
  },
  
  
];